AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  RssFeedCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function checks for whether there are new posts in the RSS feed
      CodeUri: functions/rss_feed_checker/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 * * ? *)

  LinkedInPosterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function takes a blog URL and posts it to LinkedIn
      CodeUri: functions/linkedin_poster/
      Handler: app.lambda_handler
      Runtime: python3.9

  TwitterPosterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function takes a blog URL and posts it to Twitter
      CodeUri: functions/twitter_poster/
      Handler: app.lambda_handler
      Runtime: python3.9

  BlogSyndicatorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/blog_syndicator.asl.json
      DefinitionSubstitutions:
        RssFeedCheckerFunctionArn: !GetAtt RssFeedCheckerFunction.Arn
        LinkedInPosterFunctionArn: !GetAtt LinkedInPosterFunction.Arn
        TwitterPosterFunctionArn: !GetAtt TwitterPosterFunction.Arn
      Events:
        PublishingSchedule:
          Type: Schedule
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: false
            Schedule: cron(*/10 * * * ? *)
      Policies:
      - LambdaInvokePolicy:
          FunctionName: !Ref RssFeedCheckerFunction
      - LambdaInvokePolicy:
          FunctionName: !Ref LinkedInPosterFunction
      - LambdaInvokePolicy:
          FunctionName: !Ref TwitterPosterFunction
