AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  LinkedInSecretArn:
    Type: String
    Description: The ARN of the secret containing the LinkedIn credentials
  TwitterConsumerKeyArn:
    Type: String
    Description: The ARN of the Twitter consumer key
  TwitterConsumerKeySecretArn:
    Type: String
    Description: The ARN of the Twitter consumer key secret
  TwitterAccessTokenArn:
    Type: String
    Description: The ARN of the Twitter access token
  TwitterAccessTokenSecretArn:
    Type: String
    Description: The ARN of the Twitter access token secret

Resources:
  RssFeedCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function checks for whether there are new posts in the RSS feed
      CodeUri: functions/rss_feed_checker/
      Handler: app.lambda_handler
      Runtime: python3.9

  LinkedInPosterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function takes a blog URL and posts it to LinkedIn
      CodeUri: functions/linkedin_poster/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref LinkedInSecretArn
      Environment:
        Variables:
          LINKED_IN_SECRET_ARN: !Ref LinkedInSecretArn
      
  TwitterPosterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function takes a blog URL and posts it to Twitter
      CodeUri: functions/twitter_poster/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Policies:
        - Statement:
            - Effect: "Allow"
              Action: "secretsmanager:GetSecretValue"
              Resource:
                - !Ref TwitterConsumerKeyArn
                - !Ref TwitterConsumerKeySecretArn
                - !Ref TwitterAccessTokenArn
                - !Ref TwitterAccessTokenSecretArn
      Environment:
        Variables:
          TWITTER_CONSUMER_KEY_ARN: !Ref TwitterConsumerKeyArn
          TWITTER_CONSUMER_KEY_SECRET_ARN: !Ref TwitterConsumerKeySecretArn
          TWITTER_ACCESS_TOKEN_ARN: !Ref TwitterAccessTokenArn
          TWITTER_ACCESS_TOKEN_SECRET_ARN: !Ref TwitterAccessTokenSecretArn

  BlogSyndicatorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/blog_syndicator.asl.json
      DefinitionSubstitutions:
        RssFeedCheckerFunctionArn: !GetAtt RssFeedCheckerFunction.Arn
        LinkedInPosterFunctionArn: !GetAtt LinkedInPosterFunction.Arn
        TwitterPosterFunctionArn: !GetAtt TwitterPosterFunction.Arn
      Events:
        PublishingSchedule:
          Type: Schedule
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: false
            Schedule: cron(*/10 * * * ? *)
      Policies:
      - LambdaInvokePolicy:
          FunctionName: !Ref RssFeedCheckerFunction
      - LambdaInvokePolicy:
          FunctionName: !Ref LinkedInPosterFunction
      - LambdaInvokePolicy:
          FunctionName: !Ref TwitterPosterFunction
